[package]
name = "mocktopus"
version = "0.1.0"
authors = ["CodeSandwich <igor.zuk@protonmail.com>"]
description = "Mocking framework for Rust"
readme = "crates_io_readme.md"
license = "MIT"

[badges]
travis-ci = { repository = "CodeSandwich/Mocktopus" }

[lib]
doctest = false

[dependencies]
mocktopus_macros = { path = "macros" }

[workspace]
members = ["macros"]
