[package]
name = "mocktopus"
version = "0.1.0"
authors = ["CodeSandwich <igor.zuk@protonmail.com>"]

[dev-dependencies]
mocktopus_injector = { path = "injector" }

[workspace]
members = ["injector"]

