[package]
name = "mocktopus"
version = "0.1.0"
authors = ["CodeSandwich <igor.zuk@protonmail.com>"]

[lib]
doctest = false

[dependencies]
mocktopus_macros = { path = "macros" }

[workspace]
members = ["macros"]

