[package]
name = "mocktopus_test"
version = "0.1.0"
authors = ["CodeSandwich <igor.zuk@protonmail.com>"]

[dev-dependencies]
mocktopus_macro = { path = "mocktopus_macro" }
mocktopus = { path = "mocktopus" }

[workspace]
members = ["mock_macro_test", "mocktopus", "mocktopus_macro"]

