[package]
name = "mock_experiment"
version = "0.1.0"
authors = ["CodeSandwich <igor.zuk@protonmail.com>"]

[dev-dependencies]
mock_macro = { path = "mock_macro" }
mock_trait = { path = "mock_trait" }

[workspace]
members = ["mock_macro", "mock_trait", "mock_macro_test"]

