[package]
name = "mock_macro_test"
version = "0.1.0"
authors = ["CodeSandwich <igor.zuk@protonmail.com>"]

[dependencies]
mocktopus_macro = { path = "../mocktopus_macro" }
mocktopus = { path = "../mocktopus" }
