[package]
name = "mock_macro_test"
version = "0.1.0"
authors = ["CodeSandwich <igor.zuk@protonmail.com>"]

[dependencies]
mock_macro = { path = "../mock_macro" }
mock_trait = { path = "../mock_trait" }
