[package]
name = "mock_macro"
version = "0.1.0"
authors = ["CodeSandwich <igor.zuk@protonmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "^0.11.11", features = ["full"] }
quote = "0.3.15"
